[project]
name = "data-stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "fastapi>=0.117.1",
    "confluent-kafka[avro]>=2.6.1",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
]
